artist:
  name: Oliver Barabas
  tagline:
    first: Music Producer.
    second: Web Developer.
    third: Proud Dad.
  seo_title: Oliver Barabas
  seo_description: Music Producer. Web Developer. Proud Dad.
  contact_twitter_username: oliverbarabas
  # contact_phone:
  # contact_email:

social:
  - name: Instagram
    url: https://instagram.com/obarabas
  - name: Twitter
    url: https://twitter.com/oliverbarabas
  - name: Youtube
    url: https://youtube.com/bazzdream?sub_confirmation=1
  - name: Spotify
    url: https://open.spotify.com/artist/23WPyLTvehei1DDp3TljK3
  - name: Soundcloud
    url: https://soundcloud.com/bazzdream/tracks

site_language: en
